services:
  - name: "Infraestrutura"
    icon: "fas fa-server"
    items:
      - name: "Traefik"
        logo: "assets/icons/traefik.ico"
        subtitle: "Proxy Reverso"
        url: "https://traefik-xxx.dominio.com"
        target: "_blank"
      - name: "Netdata"
        icon: "assets/icons/netdata.svg"
        subtitle: "Monitoramento"
        url: "https://netdata-xxx.dominio.com/spaces/mst-rasp/rooms/local/overview#menu_overview"
        target: "_blank"
      - name: "Portainer"
        icon: "assets/icons/portainer.svg"
        subtitle: "Gerenciamento de Containers"
        url: "https://portainer-xxx.dominio.com"
        target: "_blank"
  - name: "Ferramentas"
    icon: "fas fa-tools"
    items:
      - name: "The SVG"
        logo: "assets/icons/thesvg.svg"
        subtitle: "Gerador de icones SVG"
        url: "https://thesvg.org/icon"
        target: "_blank"
